modLoader="javafml"

loaderVersion="[35,)"

license="All rights reserved"

#issueTrackerURL="http://my.issue.tracker/"

[[mods]]

modId="mymod"
version="${file.jarVersion}"
displayName="My Mod"
updateJSONURL="https://github.com/Mynori/minecraft_mod/blob/master/update.json"
#displayURL="http://example.com/"
logoFile="mymod.png"

credits="This is my credit"
authors="minori"
description='''
This is my description
'''


[[dependencies.mymod]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mymod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
