modLoader="javafml"

loaderVersion="[31,)"

#issueTrackerURL="http://my.issue.tracker/"
updateJSONURL="https://github.com/Mynori/minecraft_mod/blob/master/update.json"

showAsResourcePack=false

# Mod
[[mods]]

modId="mymod"
version="${file.jarVersion}"
displayName="My Mod"

logoFile="mymod.png"

credits="This is my credit"
authors="minori"
description='''
This is my description
'''

# Dependencies
[[dependencies.mymod]]

    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mymod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
